apiVersion: v1
kind: Service
metadata:
  name: ai-tutor-service
  namespace: ai-tutor
spec:
  selector:
    app: ai-tutor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
